'use strict';

/**
 * Parses a steering doc file into its YAML front matter and markdown body.
 *
 * Front matter is delimited by `---` lines and contains simple key-value pairs:
 *   name, description, auto_generated
 *
 * @param {string} content - Raw file content of a steering doc
 * @returns {{ frontMatter: object, body: string }}
 */
function parseSteeringDoc(content) {
  const frontMatter = { name: '', description: '', auto_generated: false, when_files: [] };
  let body = '';

  if (typeof content !== 'string') {
    return { frontMatter, body };
  }

  const trimmed = content.trimStart();

  // Must start with --- to have front matter
  if (!trimmed.startsWith('---')) {
    return { frontMatter, body: content };
  }

  // Find the closing --- delimiter (skip the opening one)
  const afterOpening = trimmed.indexOf('\n');
  if (afterOpening === -1) {
    return { frontMatter, body: content };
  }

  const rest = trimmed.slice(afterOpening + 1);
  const closingIdx = rest.indexOf('\n---');

  if (closingIdx === -1) {
    // No closing delimiter — treat entire content as body, no front matter
    return { frontMatter, body: content };
  }

  const yamlBlock = rest.slice(0, closingIdx);
  // Body starts after the closing --- and its newline
  const afterClosing = rest.slice(closingIdx + 4); // skip '\n---'
  body = afterClosing.startsWith('\n') ? afterClosing.slice(1) : afterClosing;

  // Parse key-value pairs from the YAML block
  const lines = yamlBlock.split('\n');
  for (const line of lines) {
    const colonIdx = line.indexOf(':');
    if (colonIdx === -1) continue;

    const key = line.slice(0, colonIdx).trim();
    let value = line.slice(colonIdx + 1).trim();

    if (key === 'name') {
      frontMatter.name = value;
    } else if (key === 'description') {
      frontMatter.description = value;
    } else if (key === 'auto_generated') {
      frontMatter.auto_generated = value === 'true';
    } else if (key === 'when_files') {
      // Comma-separated glob patterns, e.g. "*.xcodeproj, *.xcworkspace"
      frontMatter.when_files = value
        .split(',')
        .map(p => p.trim())
        .filter(p => p.length > 0);
    }
  }

  return { frontMatter, body };
}

/**
 * Serializes a steering doc back to its file format (YAML front matter + markdown body).
 *
 * @param {object} frontMatter - Object with name, description, auto_generated fields
 * @param {string} body - Markdown body content
 * @returns {string}
 */
function printSteeringDoc(frontMatter, body) {
  const fm = frontMatter || {};
  const name = fm.name || '';
  const description = fm.description || '';
  const autoGenerated = fm.auto_generated === true;

  let result = '---\n';
  result += `name: ${name}\n`;
  result += `description: ${description}\n`;
  result += `auto_generated: ${autoGenerated}\n`;
  result += '---\n';

  if (body) {
    result += body;
  }

  return result;
}

/**
 * Loads all steering docs from the .maccoder/steering/ directory of a project.
 *
 * Reads every `.md` file, parses its front matter, and returns an array of
 * SteeringDoc objects. Files with malformed front matter (empty name) are
 * skipped with a console warning. Returns an empty array if the directory
 * does not exist.
 *
 * @param {string} projectDir - Absolute path to the project root
 * @returns {{ name: string, description: string, autoGenerated: boolean, body: string }[]}
 */
/**
 * Checks whether a filename matches a glob-like pattern.
 * Supports * (any chars) and ? (single char) wildcards.
 *
 * @param {string} filename
 * @param {string} pattern
 * @returns {boolean}
 */
function matchesGlob(filename, pattern) {
  // Escape regex special chars except * and ?
  const escaped = pattern.replace(/[.+^${}()|[\]\\]/g, '\\$&');
  const regexStr = '^' + escaped.replace(/\*/g, '.*').replace(/\?/g, '.') + '$';
  return new RegExp(regexStr, 'i').test(filename);
}

/**
 * Checks whether any top-level entry in projectDir matches at least one
 * of the given glob patterns. Returns true if patterns is empty (unconditional).
 *
 * @param {string} projectDir
 * @param {string[]} patterns
 * @returns {boolean}
 */
function projectMatchesWhenFiles(projectDir, patterns) {
  if (!patterns || patterns.length === 0) return true;

  const fs = require('node:fs');
  let entries;
  try {
    entries = fs.readdirSync(projectDir);
  } catch (_err) {
    return false;
  }

  for (const entry of entries) {
    for (const pattern of patterns) {
      if (matchesGlob(entry, pattern)) return true;
    }
  }
  return false;
}

function loadSteeringDocs(projectDir) {
  const fs = require('node:fs');
  const path = require('node:path');

  const steeringDir = path.join(projectDir, '.maccoder', 'steering');
  let files;
  try {
    files = fs.readdirSync(steeringDir);
  } catch (_err) {
    return [];
  }

  const docs = [];
  for (const file of files) {
    if (!file.endsWith('.md')) continue;

    const filePath = path.join(steeringDir, file);
    let content;
    try {
      content = fs.readFileSync(filePath, 'utf8');
    } catch (_err) {
      continue;
    }

    const { frontMatter, body } = parseSteeringDoc(content);

    if (!frontMatter.name) {
      console.warn(`Skipping steering doc with empty name: ${file}`);
      continue;
    }

    // Skip docs whose when_files patterns don't match any project entries
    if (!projectMatchesWhenFiles(projectDir, frontMatter.when_files)) {
      continue;
    }

    docs.push({
      name: frontMatter.name,
      description: frontMatter.description,
      autoGenerated: frontMatter.auto_generated === true,
      body,
    });
  }

  return docs;
}

/**
 * Formats loaded steering docs into a prompt-injectable string.
 *
 * Produces a `## Project Context` header followed by per-doc sub-headers
 * (`### <name>`) and their body content. Returns an empty string when the
 * input array is empty, null, or undefined (requirement 7.3: no empty
 * project context section when no docs exist).
 *
 * @param {Array<{ name: string, body: string }>} docs
 * @returns {string}
 */
function formatSteeringForPrompt(docs) {
  if (!docs || docs.length === 0) {
    return '';
  }

  let result = '## Project Context\n\n';
  for (const doc of docs) {
    result += `### ${doc.name}\n\n${doc.body}\n\n`;
  }

  return result.trimEnd();
}

// --- Exports ---

module.exports = {
  parseSteeringDoc,
  printSteeringDoc,
  loadSteeringDocs,
  formatSteeringForPrompt,
  matchesGlob,
  projectMatchesWhenFiles,
};
